name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # ou main, dependendo da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --prefix samurai-elemental

      - name: Build React App
        run: npm run build --prefix samurai-elemental

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./samurai-elemental/build # Certifique-se de que esta é a pasta de build correta
          publish_branch: gh-pages


